interface Account {
  void deposit(in unsigned long amount);
  void withdraw(in unsigned long amount);
  long balance();
};

interface Bank {
  Account create();
  void destroy(in Account a);
  Account move(in Bank target, in Account a);
};
